version: "3"

services:
  nginx:
    container_name: nginx_https
    image: nginx:1.15-alpine
    restart: unless-stopped
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    volumes:
      - ${DIR}/nginx:/etc/nginx/conf.d
      - ${DIR}/certbot/conf:/etc/letsencrypt
      - ${DIR}/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    environment:
      DIR: "{{ DIR }}"
    networks:
      infura:
        ipv4_address: 10.2.0.201

  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: unless-stopped
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    volumes:
      - ${DIR}/certbot/conf:/etc/letsencrypt
      - ${DIR}/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    environment:
      DIR: "{{ DIR }}"
    networks:
      infura:
        ipv4_address: 10.2.0.202

networks:
  infura:
    external:
      name: infura
