version: "3"

services:
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    volumes:
      - ${DIR}/nginx:/etc/nginx/conf.d
      - ${DIR}/certbot/conf:/etc/letsencrypt
      - ${DIR}/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    environment:
      DIR: "{{ DIR }}"
    networks:
      nginx-cert:
        ipv4_address: 10.3.0.101

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    volumes:
      - ${DIR}/certbot/conf:/etc/letsencrypt
      - ${DIR}/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    environment:
      DIR: "{{ DIR }}"
    networks:
      nginx-cert:
        ipv4_address: 10.3.0.102

networks:
  nginx-cert:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.3.0.0/24
